


### Security Requests



###
POST /api/v1/security/login
Host: localhost:9000
Origin: http://localhost:9000
Content-Type: application/json

{
    "email": "burgasvv@gmail.com",
    "password": "burgasvv"
}

###
POST /api/v1/security/logout
Origin: http://localhost:9000
Host: localhost:9000

###
GET /api/v1/security/authenticated
Host: localhost:9000
Accept: application/json



### Identity Requests



###
GET /api/v1/identities
Host: localhost:9000
Accept: application/json

###
GET /api/v1/identities/by-id?identityId=8a107c4f-8e76-4ea4-830a-56ccfca4bdcc
Host: localhost:9000
Accept: application/json

###
POST /api/v1/identities/create
Host: localhost:9000
Origin: http://localhost:9000
Content-Type: application/json

{
    "email": "zagor@gmail.com",
    "password": "zagor",
    "phone": "+79456328574",
    "firstname": "Загорулько",
    "lastname": "Борис",
    "patronymic": "Юрьевич"
}

###
PUT /api/v1/identities/update
Host: localhost:9000
Origin: http://localhost:9000
Content-Type: application/json

{
    "id": "777657f0-ff46-4d1b-8a2b-14af2946efd2",
    "telegram": "zagorT",
    "whatsapp": "zagorW",
    "max": "zagorMax"
}



### Home Requests



###
GET /api/v1/homes
Host: localhost:9000

###
GET /api/v1/homes/by-free
Host: localhost:9000

###
GET /api/v1/homes/by-id?homeId=e0c14fa3-4840-427d-bde6-62a5d2ebfa05
Host: localhost:9000

###
POST /api/v1/homes/create
Host: localhost:9000
Origin: http://localhost:9000
Content-Type: application/json

{
    "homeType": "APARTMENT",
    "address": {
        "country": "Россия",
        "city": "Новосибирск",
        "street": "Российская",
        "building": "30/4",
        "apartment": "12"
    },
    "description": "Описание квартиры",
    "billingUnit": "MONTHLY",
    "price": 25500.0,
    "lessorId": "8a107c4f-8e76-4ea4-830a-56ccfca4bdcc"
}

###
PUT /api/v1/homes/update
Host: localhost:9000
Origin: http://localhost:9000
Content-Type: application/json

{
    "id": "e0c14fa3-4840-427d-bde6-62a5d2ebfa05",
    "address": {
        "id": "eeab13fa-dd2f-40e0-9abb-32abc16a860d",
        "apartment": "56B"
    }
}

###
PUT /api/v1/homes/rent
Host: localhost:9000
Origin: http://localhost:9000
Content-Type: application/json

{
    "id": "e0c14fa3-4840-427d-bde6-62a5d2ebfa05",
    "tenantId": "777657f0-ff46-4d1b-8a2b-14af2946efd2"
}

###
PUT /api/v1/homes/cancel?homeId=e0c14fa3-4840-427d-bde6-62a5d2ebfa05
Host: localhost:9000
Origin: http://localhost:9000